name: Update Gapper Data

on:
  schedule:
    # Runs at 9 PM UK time (4 PM EST)
    - cron: '0 21 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install pandas numpy requests pytz
    
    - name: Run data collector
      env:
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
      run: |
        python update_data.py
    
    - name: Check if data file was created
      run: |
        if [ -f "data/gapper_stats.json" ]; then
          echo "Data file created successfully"
          ls -la data/
        else
          echo "ERROR: Data file was not created"
          exit 1
        fi
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add data/gapper_stats.json
        git diff --staged --quiet && echo "No changes to commit" || (git commit -m "Update gapper data" && git push)
