name: Update Gap Data

on:
  schedule:
    - cron: '0 22 * * 1-5'  # 6 PM EST weekdays
  workflow_dispatch:

permissions:
  contents: write  # Allow writing to repository

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy pytz
    
    - name: Run detailed data collector
      env:
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
      run: python update_data.py
    
    - name: Check if data file was created
      run: |
        if [ -f "gap_data_cache.json" ]; then
          echo "✅ Data file created successfully"
          ls -la gap_data_cache.json
        else
          echo "❌ ERROR: Data file was not created"
          exit 1
        fi
    
    - name: Validate JSON structure
      run: |
        if python -c "import json; json.load(open('gap_data_cache.json'))"; then
          echo "✅ JSON structure is valid"
        else
          echo "❌ ERROR: Invalid JSON structure"
          exit 1
        fi
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add gap_data_cache.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update gap data cache [$(date)]"
          git push
        fi
